version: '3.9'

services:
  ui:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
    networks:
      - web-ui

networks:
  web-ui:
