version: '3.9'

services:
  portfolio_ui:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ConnectionStrings__PostgreSqlConnection=Server=postgresql;Database=Portfolio;Port=5432;User Id=postgres;Password=12345;
    volumes:
      - /root/Sarvar/DB:/app/DB
      - /root/Sarvar/Files:/app/Files
    ports:
      - "4200:4200"
    networks:
      - web
